name = "Slacker"
uuid = "1fee779b-79a2-446d-a52f-d1aa38b3d5ab"
authors = ["André Calero Valdez", ""]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
